# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-MZsCeYd_t5ZzkYTinyVRaZcP-0flI9
"""

pip install python-docx

import re
import sys
from docx import Document

def chunk_text_by_sentences(text):
    """
    Chunks text into sentences using regex pattern matching.
    Handles common sentence endings: . ! ?
    """
    # Pattern to split on sentence boundaries
    # Looks for . ! or ? followed by space and uppercase letter, or end of string
    sentence_pattern = r'(?<=[.!?])\s+(?=[A-Z])|(?<=[.!?])$'

    sentences = re.split(sentence_pattern, text.strip())

    # Remove empty strings and clean whitespace
    sentences = [s.strip() for s in sentences if s.strip()]

    return sentences


def chunk_file(file_path):
    """
    Reads a .docx or .txt file and chunks it into sentences.
    """
    try:
        if file_path.endswith('.docx'):
            # Read from .docx file
            doc = Document(file_path)
            text = '\n'.join([paragraph.text for paragraph in doc.paragraphs])
        else:
            # Read from .txt file
            with open(file_path, 'r', encoding='utf-8') as file:
                text = file.read()

        sentences = chunk_text_by_sentences(text)
        return sentences

    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return []
    except Exception as e:
        print(f"Error reading file: {e}")
        return []


def save_chunks(sentences, output_file):
    """
    Saves chunked sentences to an output file as a Python list.
    """
    try:
        with open(output_file, 'w', encoding='utf-8') as file:
            file.write("chunks = [\n")
            for sentence in sentences:
                # Escape quotes in sentences
                escaped_sentence = sentence.replace('"', '\\"')
                file.write(f'    "{escaped_sentence}",\n')
            file.write("]\n")
        print(f"Successfully saved {len(sentences)} sentences to '{output_file}'")
    except Exception as e:
        print(f"Error saving file: {e}")


def print_chunks(sentences, max_display=None):
    """
    Prints chunks to console.
    """
    display_count = max_display if max_display else len(sentences)
    for i, sentence in enumerate(sentences[:display_count], 1):
        print(f"{i}. {sentence}\n")

    if max_display and len(sentences) > max_display:
        print(f"... and {len(sentences) - max_display} more sentences")


# Main execution
if __name__ == "__main__":
    # Example usage
    input_file = "input.docx"  # Change this to your .docx or .txt file path
    output_file = "output_chunks.txt"  # Output file name

    print(f"Reading from: {input_file}")
    sentences = chunk_file(input_file)

    if sentences:
        print(f"\nTotal sentences found: {len(sentences)}\n")
        print("First 5 sentences:")
        print_chunks(sentences, max_display=5)

        # Save to output file
        save_chunks(sentences, output_file)
    else:
        print("No sentences found or file could not be read.")

